#!/bin/sh
# Build a deterministic, standalone Enigma2 IPK from the stable source tree.
set -eu

die() {
    printf '%s\n' "build-ipk.sh: $*" >&2
    exit 1
}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
PROJECT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd -P)
PLUGIN_ROOT="$PROJECT_ROOT/GTIPTVPlayerPro"
CONTROL_ROOT="$PROJECT_ROOT/CONTROL"
DEFAULT_OUTPUT="$PROJECT_ROOT/dist/enigma2-plugin-extensions-gtiptvplayerpro_1.1.0-r0_all.ipk"

if [ "$#" -gt 1 ]; then
    die 'usage: build-ipk.sh [output.ipk]'
fi

OUTPUT=${1:-$DEFAULT_OUTPUT}
case "$OUTPUT" in
    /*) ;;
    *) OUTPUT="$(pwd -P)/$OUTPUT" ;;
esac

# A fixed fallback keeps ordinary local builds reproducible.  Release builds
# may (and CI does) supply a project-wide SOURCE_DATE_EPOCH explicitly.
SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH:-1700000000}
case "$SOURCE_DATE_EPOCH" in
    ''|*[!0-9]*) die 'SOURCE_DATE_EPOCH must be a non-negative integer' ;;
esac

command -v ar >/dev/null 2>&1 || die 'GNU ar is required'
command -v tar >/dev/null 2>&1 || die 'GNU tar is required'
command -v gzip >/dev/null 2>&1 || die 'gzip is required'
command -v sort >/dev/null 2>&1 || die 'sort is required'
case "$(tar --version 2>/dev/null || true)" in
    *GNU\ tar*) ;;
    *) die 'GNU tar is required' ;;
esac

[ -d "$PLUGIN_ROOT" ] && [ ! -L "$PLUGIN_ROOT" ] || die 'plugin root is missing or unsafe'
[ -d "$CONTROL_ROOT" ] && [ ! -L "$CONTROL_ROOT" ] || die 'CONTROL root is missing or unsafe'
for CONTROL_FILE in control postinst postrm; do
    CONTROL_PATH="$CONTROL_ROOT/$CONTROL_FILE"
    [ -f "$CONTROL_PATH" ] && [ ! -L "$CONTROL_PATH" ] ||
        die "CONTROL/$CONTROL_FILE is missing or unsafe"
done

# Resolve the destination before staging.  Keeping output outside both input
# trees prevents a previous package from becoming part of a later payload.
OUTPUT_DIR=$(dirname -- "$OUTPUT")
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR=$(CDPATH= cd -- "$OUTPUT_DIR" && pwd -P) ||
    die 'could not resolve output directory'
OUTPUT="$OUTPUT_DIR/$(basename -- "$OUTPUT")"
case "$OUTPUT" in
    "$PLUGIN_ROOT"|"$PLUGIN_ROOT"/*|"$CONTROL_ROOT"|"$CONTROL_ROOT"/*)
        die 'output must be outside GTIPTVPlayerPro and CONTROL'
        ;;
esac
if [ -d "$OUTPUT" ] || [ -L "$OUTPUT" ]; then
    die 'output must be a regular file path, not a directory or symlink'
fi
if [ -e "$OUTPUT" ] && [ ! -f "$OUTPUT" ]; then
    die 'output exists and is not a regular file'
fi

# The package contract contains directories and regular files only.  Rejecting
# all other input types prevents symlink traversal and host-specific archive
# contents; this check also covers excluded cache directories.
UNSAFE_PATH=$(find "$PLUGIN_ROOT" -xdev \( -type l -o \( ! -type d -a ! -type f \) \) -print -quit)
if [ -n "$UNSAFE_PATH" ]; then
    die "plugin tree contains a symlink or non-regular entry: $UNSAFE_PATH"
fi

BUILD_DIR=$(mktemp -d "$PROJECT_ROOT/.ipk-build.XXXXXX") || die 'could not create build directory'
trap 'rm -rf "$BUILD_DIR"' EXIT HUP INT TERM

CONTROL_STAGE="$BUILD_DIR/control"
DATA_STAGE="$BUILD_DIR/data"
PLUGIN_STAGE="$DATA_STAGE/usr/lib/enigma2/python/Plugins/Extensions/GTIPTVPlayerPro"
mkdir -p "$CONTROL_STAGE" "$PLUGIN_STAGE"

cp "$CONTROL_ROOT/control" "$CONTROL_STAGE/control"
cp "$CONTROL_ROOT/postinst" "$CONTROL_STAGE/postinst"
cp "$CONTROL_ROOT/postrm" "$CONTROL_STAGE/postrm"

# Make the staging payload from an explicit, sorted member list.  In
# particular, never package generated bytecode, editor rejects or rollback
# copies accidentally left beside the canonical runtime.
(
    cd "$PLUGIN_ROOT"
    find . -xdev \
        \( -type d -name __pycache__ -o -type f \( \
            -name '*.pyc' -o -name '*.pyo' -o -name '*.bak' \
            -o -name '*.orig' -o -name '*.rej' \
        \) \) -prune -o \
        \( -type d -o -type f \) -print0 > "$BUILD_DIR/payload.unsorted"
)
LC_ALL=C sort -z "$BUILD_DIR/payload.unsorted" > "$BUILD_DIR/payload.members"
(
    cd "$PLUGIN_ROOT"
    tar --null --no-recursion -T "$BUILD_DIR/payload.members" -cf "$BUILD_DIR/payload.tar"
)
tar -C "$PLUGIN_STAGE" -xf "$BUILD_DIR/payload.tar"

# Do not inherit a developer's umask, ownership, or executable bits.  The
# final tar commands also force numeric root ownership and the fixed mtime.
find "$CONTROL_STAGE" -type d -exec chmod 0755 {} \;
find "$CONTROL_STAGE" -type f -exec chmod 0644 {} \;
chmod 0755 "$CONTROL_STAGE/postinst" "$CONTROL_STAGE/postrm"
find "$DATA_STAGE" -type d -exec chmod 0755 {} \;
find "$DATA_STAGE" -type f -exec chmod 0644 {} \;

(
    cd "$CONTROL_STAGE"
    find . -print0 > "$BUILD_DIR/control.unsorted"
)
LC_ALL=C sort -z "$BUILD_DIR/control.unsorted" > "$BUILD_DIR/control.members"
(
    cd "$CONTROL_STAGE"
    tar --null --no-recursion -T "$BUILD_DIR/control.members" --format=gnu \
        --mtime="@$SOURCE_DATE_EPOCH" --owner=0 --group=0 --numeric-owner \
        -cf "$BUILD_DIR/control.tar"
)
gzip -9 -n -c "$BUILD_DIR/control.tar" > "$BUILD_DIR/control.tar.gz"

(
    cd "$DATA_STAGE"
    find . -print0 > "$BUILD_DIR/data.unsorted"
)
LC_ALL=C sort -z "$BUILD_DIR/data.unsorted" > "$BUILD_DIR/data.members"
(
    cd "$DATA_STAGE"
    tar --null --no-recursion -T "$BUILD_DIR/data.members" --format=gnu \
        --mtime="@$SOURCE_DATE_EPOCH" --owner=0 --group=0 --numeric-owner \
        -cf "$BUILD_DIR/data.tar"
)
gzip -9 -n -c "$BUILD_DIR/data.tar" > "$BUILD_DIR/data.tar.gz"

printf '2.0\n' > "$BUILD_DIR/debian-binary"
ar rcsD "$BUILD_DIR/package.ipk" "$BUILD_DIR/debian-binary" \
    "$BUILD_DIR/control.tar.gz" "$BUILD_DIR/data.tar.gz"
chmod 0644 "$BUILD_DIR/package.ipk"
mv -f "$BUILD_DIR/package.ipk" "$OUTPUT"

printf '%s\n' "$OUTPUT"
